name: SQL Scanner Pipeline

trigger:
  branches:
    include:
    - master
    - develop
  paths:
    include:
    - sql_scripts/**
    - rules/**
    - *.py
    - requirements.txt
    - config.yaml

pool:
  vmImage: 'ubuntu-latest'

variables:
  python.version: '3.9'

stages:
- stage: Scan
  displayName: 'Scan SQL Files'
  jobs:
  - job: ScanSQL
    displayName: 'Run SQL Scanner'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
        addToPath: true

    - script: |
        python -m pip install --upgrade pip
      displayName: 'Upgrade pip'

    - script: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
      displayName: 'Install dependencies'

    - script: |
        source venv/bin/activate
        python sql_scanner.py -s sql_scripts -r rules --report-format html json
      displayName: 'Run SQL Scanner'

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: 'reports'
        artifact: 'scan-reports'
        publishLocation: 'pipeline'
      displayName: 'Publish Scan Reports' 