image: python:3.9

definitions:
  steps:
    - step: &scan-sql
        name: Scan SQL Files
        caches:
          - pip
        script:
          - python -m venv venv
          - source venv/bin/activate
          - pip install -r requirements.txt
          - python sql_scanner.py -s sql_scripts -r rules --report-format html json
        artifacts:
          - reports/**

pipelines:
  default:
    - step: *scan-sql
  branches:
    develop:
      - step: *scan-sql
    master:
      - step: *scan-sql
  pull-requests:
    '**':
      - step: *scan-sql 