name: SQL Scanner

on:
  push:
    branches: [ master, develop ]
    paths:
      - 'sql_scripts/**'
      - 'rules/**'
      - '*.py'
      - 'requirements.txt'
      - 'config.yaml'
  pull_request:
    branches: [ master, develop ]
    paths:
      - 'sql_scripts/**'
      - 'rules/**'
      - '*.py'
      - 'requirements.txt'
      - 'config.yaml'

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Run SQL Scanner
      run: |
        source venv/bin/activate
        python sql_scanner.py -s sql_scripts -r rules --report-format html json

    - name: Upload scan reports
      uses: actions/upload-artifact@v2
      with:
        name: scan-reports
        path: reports/ 